### PR TITLE
Add Code of conduct

### PR DESCRIPTION
**Pull request by rizwankce**
standard COC from Contributor Covenant.

### CODE REVIEW

**Comment by rizwankce** [comment]
Added your twitter [link](https://twitter.com/icanzilb) for contact. We could have other mode of contact if you wish.

**Comment by icanzilb** [comment]
Thanks @rizwankce, this is useful and necessary. I'm wondering if the policy as described is, in fact, applicable on GitHub? For example:

```
A permanent ban from any sort of public interaction within
the community.
```

I'm not sure if there's a way to ban accounts from interacting with an open source repo?

**Comment by rizwankce** [comment]
@icanzilb there is option from GitHub to add it automatically by providing only the contact person link.

https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project

I have followed above. I guess permanent ban would be from repo wise. I need to check how other repos does the restrictions.

**Comment by rizwankce** [comment]
So indeed it's possible. TIL

**Review by icanzilb — APPROVED** [review]

**Pull request merged**
