### PR TITLE
Add ci.yml for Github actions

### LINKED ISSUE #8: Setup GitHub CI
- we need running the tests upon pushing or merging

### PR DESCRIPTION
**Pull request by rizwankce**
closed #8 

I have used specific Xcode beta to get Swift 5.7. However once we support older versions of swift, we have to revisit this. Probably add a matrix with all swift versions.

### CODE REVIEW

**Comment by icanzilb** [comment]
Hey @rizwankce thanks a ton for opening this PR. Would the dual 5.6 / 5.7 setup be way more complex that what you have now? Would it make sense to wait out https://github.com/icanzilb/MarkCodable/pull/16 before moving forward with the CI setup? What do you think?

**Comment by rizwankce** [comment]
it won't be much change. Something like this below in `ci.yml`

```
strategy:
  matrix:
    swift: ["5.6", "5.7"]
  container:
     image: swift:${{ matrix.swift }}
```

I guess we can wait till swift 5.6 support landing in main branch. 

Also one more question, do you think we need to support linux?

**Comment by icanzilb** [comment]
Oh my god, that's a great question ... now that you're asking, I think this package could be very useful for automation or for other tooling that might be running on Linux indeed.

**Comment by rizwankce** [comment]
We can spin up a test run on linux as well. There might some small changes (sometime no change) to support linux. Let's see

**Comment by icanzilb** [comment]
Seems that 5.7 isn't available on Ubuntu for GitHub actions (https://github.com/rizwankce/MarkCodable/runs/8221328969?check_suite_focus=true), I'd be fine with having macOS/5.6, macOS/5.7 and Ubuntu/5.6 for the moment and we'll create another issue to add Ubuntu/5.7 in the future - does that sound good?

**Comment by rizwankce** [comment]
@icanzilb yup. just found out that in hard way. Im gonna make some changes and Make it ready for review

**Comment by rizwankce** [comment]
@icanzilb I made some changes to run linux and macOS in different job so one failure won't pause other jobs. [test run](https://github.com/rizwankce/MarkCodable/runs/8221624743?check_suite_focus=true)
For now all tests are passing on macOS - 5.6 and 5.7 and linux - 5.6. We can add 5.7 linux when its ready.

**Review by icanzilb — APPROVED** [review]
This is great, thanks for setting that up!

**Pull request merged**
